### PR TITLE
Yearly updates :)

### PR DESCRIPTION
**Pull request by nviennot**

### CODE REVIEW

**Comment by nviennot** [comment]
Hold on don't merge yet
I'm not done

**Comment by mglukhovsky** [comment]
@nviennot, sorry we haven't gotten around to this -- @deontologician might be a better person to look at it.

We'll wait for your changes! :smiley:

**Comment by nviennot** [comment]
You can merge :)

**Comment by mglukhovsky** [comment]
Thanks! @deontologician, when you get a chance, could you take a look at this?

**Comment by deontologician** [comment]
Looks good, merging

**Pull request merged**
